const
  WINDOW_HEIGHT* = 600
  WINDOW_WIDTH* = 800
  WINDOW_TITLE* = "Nim Breakout"
  BALL_SIZE* = 30
  BALL_SPEED*: float32 = 500
  FPS* = 60
  DELTA_TIME_SEC*: float32 = 1.0 / float32(FPS)
  BAR_LENGTH*: float32 = 100
  BAR_THICKNESS*: float32 = float32(BALL_SIZE) / 2
  BAR_Y*: float32 = WINDOW_HEIGHT - BAR_THICKNESS - 100
  BAR_SPEED*: float32 = BALL_SPEED
  TARGET_WIDTH*: float32 = BAR_LENGTH
  TARGET_HEIGHT*: float32 = BAR_THICKNESS
  TARGETS_CAP* = 128
  TARGET_PADDING* = 20